### PR TITLE
feat(directory listing)finish dir.listing implementation, fix routing…

### PR DESCRIPTION
**Pull request by lmangall**
1. start with default configuration,
2. access` www.example.com`
3. delete` index.html` under `www.example.com`
4. reload and witness directory listing

The routing is not perfect, but I think it is better to do small PRs

### CODE REVIEW

**Comment by dantol29** [comment]
@lmangall I fixed everything! Sorry for pushing directly to your branch!

**Comment by dantol29** [comment]
How can I witness directory listing?

**Comment by lmangall** [comment]
@dantol29  Amazing, thanks for the fixes!
I described how to see directory listing in the PR description :

> start with default configuration,
> access www.example.com
> delete index.html under www.example.com
> reload and witness directory listing

You have to acces a directory that holds other files (preferably), but no index.html, and no index page set in the server block, but naturally auto index on on the serverblock

**Comment by dantol29** [comment]
It works! Nice!
image

**Review by dantol29 — APPROVED** [review]
Super! As I understand proper multi-server logic will be implemented in the next PR!
So far everything works for both Chrome and Firefox!

**Comment by lmangall** [comment]
> Super! As I understand proper multi-server logic will be implemented in the next PR!

Yes that's correct, a few little things still have to be done tbh

**Review by 552020 — APPROVED** [review]
LGTM

**Pull request merged**
