### PR TITLE
sub slombard/web 93 fix compiling errors on main

### PR DESCRIPTION
**Pull request by 552020**
With exit fixed. EXIT_FAILURE is part of <stdlib.h>. Sorry I didn't check it with Linux.

### CODE REVIEW

**Review by lmangall — DISMISSED** [review]
LGTM
(I thought you would pull this branch to yours which already has a PR open, that's why I didn't opened a pR for this one myself)

**Comment by 552020** [comment]
I don't know why I did this way. When I did it 5 minutes ago it made sense. Branch has conflicts anyway ...

**Comment by 552020** [comment]
Conflicts solved.

**Review by dantol29 — APPROVED** [review]
I had to add #include <cstdlib> for exit(), but this is also works.

**Comment by lmangall** [comment]
@dantol29 Really strange, for me it compiled right off, (I purposely waited to be at school before checking)

**Review by lmangall — APPROVED** [review]
LGTM!

**Pull request merged**
