### PR TITLE
fix errors

### PR DESCRIPTION
**Pull request by 552020**
Check if the fix is correct, cause it is in "your" files. I mean above all @lmangall.

### CODE REVIEW

**Comment by lmangall** [comment]
Apparently it's not happy about this macro (is it a macro ?)
```
src/CGI_handler.cpp:11:14: error: use of undeclared identifier 'EXIT_FAILURE'
        exit(EXIT_FAILURE);
             ^
src/CGI_handler.cpp:17:14: error: use of undeclared identifier 'EXIT_FAILURE'
        exit(EXIT_FAILURE);
             ^
src/CGI_handler.cpp:27:22: error: use of undeclared identifier 'EXIT_FAILURE'
                exit(EXIT_FAILURE);
```

I noticed this comment in the main:
#include <cstdlib> // For exit() and EXIT_FAILURE

probably a linux/mac difference

**Comment by 552020** [comment]
The problem was the startWith not being defined and some guards #ifndef not being defined.

**Comment by 552020** [comment]
@lmangall

**Comment by 552020** [comment]
Please accept the PR.

**Comment by lmangall** [comment]
The problem on my side is elsewhere, what I wrote on my last message, if you want I can push with these changes

On the picture it's a fresh clone, after solving this problem it will complain about exit vs _exit, after that it was good...
image

**Comment by lmangall** [comment]
I created a sub branch with the changes I mentioned in my first message if you want to pull it to this one:
`sub-slombard/web-93-fix-compiling-errors-on-main`

**Comment by 552020** [comment]
Closing this one and opening a new PR with exit fixed. thank you @lmangall for fixing this and sorry I didn't get it at the beginning!

**Comment by lmangall** [comment]
No problem, you couldn't easilly know,

**Pull request closed without merging**
