### PR TITLE
Lmangall/web 66 create a src folder

### PR DESCRIPTION
**Pull request by lmangall**
Please accept those PRs first:
https://github.com/dantol29/webserver/pull/82
https://github.com/dantol29/webserver/pull/80

Now we can work on the code with decided standards and well organized.

### CODE REVIEW

**Comment by dantol29** [comment]
I thought we wanted to keep class.hpp and class.cpp in the same folder.

- Stefano @552020 
`A class will be separated in two files: MyClass.hpp and MyClass.cpp (both files will be in the same directory)`

**Comment by lmangall** [comment]
indeed,` Environment.hpp HTTPRequest.hpp` are going to `src/`

**Review by 552020 — CHANGES_REQUESTED** [review]
Conflicts!

**Comment by dantol29** [comment]
@552020 I thought HTTPRequst.cpp and .hpp go to /include

**Comment by lmangall** [comment]
In the case of a class,
Do we want the .cpp in the include dir or the .hpp in the src dir ?
At the moment I did .hpp in the src dir...
I am fine with both

**Comment by lmangall** [comment]
I checked a few peers code and they all have them separated: .hpp in include, .cpp in src, only Theo[ has a class folder in src](https://github.com/theozanchi/42_Berlin_webserv/tree/main/src), but he also separates

**Comment by 552020** [comment]
> In the case of a class, Do we want the .cpp in the include dir or the .hpp in the src dir ? At the moment I did .hpp in the src dir... I am fine with both

.cpp in include is not a viable solution (I guess) but .hpp wherever its .cpp peer is: .hpp in src is perfect! Thanks!

**Review by 552020 — CHANGES_REQUESTED** [review]
Could you add also src to the includes -I.src in the Makefile so that we can just write #include "MyClass.hpp"? Thanks!

**Comment by lmangall** [comment]
Done, it should be ready to pull then

**Review by 552020 — APPROVED** [review]
LGTM

**Review by dantol29 — APPROVED** [review]
Looks good

**Pull request merged**
