### PR TITLE
Add a .gitignore file

### PR DESCRIPTION
**Pull request by 552020**
It's just a suggestion, if you have your own .gitignore we can compare and 'merge' them

### CODE REVIEW

**Review by dantol29 — APPROVED** [review]
Looks good!

**Review by lmangall — COMMENTED** [review]
beautifull

**Review by lmangall — APPROVED** [review]

**Review by lmangall — APPROVED** [review]
LGTM!

**Comment by lmangall** [comment]
Somehow my approval is not enough, any ideas ?
Screenshot 2024-03-27 at 09 33 18

**Pull request merged**
