### PR TITLE
Slombard/web 193 add automatic response check in testscpp

### PR DESCRIPTION
**Pull request by 552020**
Now tests.cpp is checking automatically if the status code of the response matches with the expected status code. I also changed the char * with C++ strings. 

The file tests.cpp has been moved into the tests folder, the config tests in a config dir inside the tests dir. 
The previous tests.cpp has been saved as tests_1.cpp. tests_0.cpp is the original one.

### CODE REVIEW

**Review by dantol29 — DISMISSED** [review]
I tested it, looks great! Now it is way easier to test!

LGTM!

**Comment by 552020** [comment]
There were some conflicts here that I solved. Some config file tests was present in main. It needs again two approvals: @dantol29 and @lmangall

**Review by dantol29 — APPROVED** [review]
COOL!

**Review by lmangall — APPROVED** [review]
LGTM!

**Pull request merged**
