### PR TITLE
Slombard/web 220 add documentation on how to run general testspy

### PR DESCRIPTION
**Pull request by dantol29**
@552020 Made an awesome documentation on how to setup virtual environment for python and install all the necessary packages.
@dantol29 Removed unnecessary packages, slightly modified the documentation and added general description to `tests.md`

### CODE REVIEW

**Review by 552020 — APPROVED** [review]
LGTM

**Review by lmangall — APPROVED** [review]
LGTM!

**Comment by lmangall** [comment]
@dantol29  you got conflicts

**Review by 552020 — APPROVED** [review]
Again!

**Review by lmangall — APPROVED** [review]
LGTM!

**Pull request merged**
