### PR TITLE
Docs about http input and output parsing

### PR DESCRIPTION
**Pull request by dantol29**
Documentation is _almost ready_. I created this pull request just for you to see the information I collected. **DO NOT REVIEW YET!**

This week I will try to finish request line parsing.

### CODE REVIEW

**Comment by 552020** [comment]
Do you have any linear issue connected with this PR/Issue? @dantol29

**Comment by dantol29** [comment]
@552020 Yes, it is connected to an issue on linear

**Comment by lmangall** [comment]
@552020 it's WEB-28 
https://linear.app/web-serv/issue/WEB-28/add-docs-about-http-input-and-output-parsing

**Review by lmangall — APPROVED** [review]
I wasn't sure if we had to accept it yet, but good that I see it now because I was actually wondering about `request targer`

**Pull request merged**
