### PR TITLE
Slombard/web 221 fix copy assignment operator and check the copy constructor

### PR DESCRIPTION
**Pull request by 552020**
I'm retryting this after rebase!

### CODE REVIEW

**Review by dantol29 — APPROVED** [review]
LGTM!

**Review by lmangall — APPROVED** [review]
LR(ebased)TM!

**Comment by 552020** [comment]
And again ... there were little conflicts to solve with main. @lmangall @dantol29

**Review by lmangall — APPROVED** [review]
LU(nconflicted)TM

**Review by dantol29 — APPROVED** [review]
OK!

**Pull request merged**
