### PR TITLE
slombard/web 221 fix copy assignment operator and check the copy constructor

### PR DESCRIPTION
**Pull request by 552020**
I added the missing properties in the copy constructor and in the copy assignment operator  of the Connection object, that should fix the bug that you hadn't the time to check - but there was one! I also wrote a copy assignement operator and copy constructor for the HTTPResponse object since it is a property of Connection and the copy constructor and copy assignment operators of HTTPResponse were private. 

Please check that everything is working properly after these changed.

### CODE REVIEW

**Review by dantol29 — DISMISSED** [review]
I checked with python tester and everything works!

We have to integrate it to GitHub Actions!

**Review by lmangall — APPROVED** [review]
Great!

**Comment by 552020** [comment]
We get again this error: the merge-base changed after approval.

**Review by dantol29 — DISMISSED** [review]
LGTM! REBASEEE

**Pull request closed without merging**
