### PR TITLE
Dtolmaco/web 298 limit client body size and fix multiple server block logic

### PR DESCRIPTION
**Pull request by dantol29**
- [x] Limit client body size if `client_max_body_size` is defined

- [x] Fix multiple server block logic in `buildResponse`

- [x] Fix `index` directive logic in the Router

- [x] Add `allow_methods` logic

- [x] Fix `error_page`

- [x] `client_max_body_size` working in locations

- [x] Implement "location" logic in the Router

- [x] add `return` directive for redirection

- [x] add multiple `server_name` support

### CODE REVIEW

**Comment by lmangall** [comment]
@dantol29  it's written as a WIP, is this accurate ?
on your PR descriptions you have both bulletpoints `-`  and checks `[x]` that's why it looks weird

**Comment by dantol29** [comment]
@lmangall Index.html logic is strange, we should double check it. I did not write index directive in the config file and I got invalid path, however localhost:8080 has index.html

**Comment by dantol29** [comment]
@lmangall @552020 Lots of urgent fixes

**Review by lmangall — DISMISSED** [review]
On linear Stefano mentioned adding a test for it

**Review by lmangall — DISMISSED** [review]
LGTM!

**Comment by dantol29** [comment]
@552020 PM, common!

**Comment by dantol29** [comment]
@lmangall Sorry! Added `return` directive to the Config file to implement redirection

**Review by 552020 — APPROVED** [review]
🥗

**Review by lmangall — APPROVED** [review]
LGTM!

**Pull request merged**
