### PR TITLE
implement non blocking and multiconnection capabilities with poll (and a bunch of other stuff)

### PR DESCRIPTION
**Pull request by 552020**
- Opening the PR only for visibility: NOT meant to be merged (yet)

- There are some new classes:
- An HTTPResponse class (instead of the response string in main)
- A Server class (taking over the relevant functions of the server)
- A Router class, which checks if a path exist and select the proper request handling object to call to handle the request
- A ARequestHandler, abstract class, which have two derived classes:
- StaticContentHandler, for all files, which can be server the way they are (*.htm)
- CGIHandler, for all .php, .py, .pl, .cgi files and in general any files needing some sort CGI elaboration.

The code is still a mess, it does compile, but it's not tested and besides starting the server (which it does), it probably doesn't work and it's merged with the last main. 

Above all the CGIHandler is a super stub, just waiting for Leo to take it over.

### CODE REVIEW

**Comment by lmangall** [comment]
I get an error on compilation (on a fresh clone), perhaps it is on my side, are you using a VM ?
```
➜  webserver git:(slombard/web-36-implement-non-blocking-and-multiconnection-capabilities-with) make
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/main.cpp -o obj/src/main.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/CGI_handler.cpp -o obj/src/CGI_handler.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/CGIHandler.cpp -o obj/src/CGIHandler.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/Environment.cpp -o obj/src/Environment.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/utils.cpp -o obj/src/utils.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/HTTPRequest.cpp -o obj/src/HTTPRequest.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/HTTPResponse.cpp -o obj/src/HTTPResponse.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/HTTPRequestUtils.cpp -o obj/src/HTTPRequestUtils.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/Router.cpp -o obj/src/Router.o
c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/server_utils.cpp -o obj/src/server_utils.o
make: *** No rule to make target `obj/src/Server.o', needed by `webserv'.  Stop.
```

**Comment by lmangall** [comment]
> Above all the CGIHandler is a super stub, just waiting for Leo to take it over.

I assume you are talking about var/www (and are being humble)

...or are you being ironic and talking about :
```
HTTPResponse CGIHandler::handleRequest(const HTTPRequest &request)
{
	(void)request;
	HTTPResponse response;
	// Determine CGI script path and set up environment
	return response;
}
```

**Comment by 552020** [comment]
> I get an error on compilation (on a fresh clone), perhaps it is on my side, are you using a VM ?
> 
> ```
> ➜  webserver git:(slombard/web-36-implement-non-blocking-and-multiconnection-capabilities-with) make
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/main.cpp -o obj/src/main.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/CGI_handler.cpp -o obj/src/CGI_handler.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/CGIHandler.cpp -o obj/src/CGIHandler.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/Environment.cpp -o obj/src/Environment.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/utils.cpp -o obj/src/utils.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/HTTPRequest.cpp -o obj/src/HTTPRequest.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/HTTPResponse.cpp -o obj/src/HTTPResponse.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/HTTPRequestUtils.cpp -o obj/src/HTTPRequestUtils.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/Router.cpp -o obj/src/Router.o
> c++ -Wall -Wextra -Werror -std=c++98 -I. -Iinclude -Isrc -MMD -MP -c src/server_utils.cpp -o obj/src/server_utils.o
> make: *** No rule to make target `obj/src/Server.o', needed by `webserv'.  Stop.
> ```


The problem here is the file server.cpp, that should be renamed in Server.cpp. Some systems and git has an hard time to differenciate between capitalized and not capitalized file names. I guess git doesn't report the change. We should rename to something else and then back to Server.cpp to have it capitalized.

**Comment by 552020** [comment]
> > Above all the CGIHandler is a super stub, just waiting for Leo to take it over.
> 
> I assume you are talking about var/www (and are being humble)
> 
> ...or are you being ironic and talking about
> 
> ```
> HTTPResponse CGIHandler::handleRequest(const HTTPRequest &request)
> {
> 	(void)request;
> 	HTTPResponse response;
> 	// Determine CGI script path and set up environment
> 	return response;
> }
> ```
> 
> Sincerely asking 😁

The CGIHandler is a super mess

image

It has two different methods, but we want to have just one and we have also your original function which is the one working

image

I mean it's not a big deal. This function should be copied as a method and then you should check if it makes sense that the function gives back an HTTPResponse object or a string. I'm not sure about which kind of response you are supposed to get back from the CGI thing. I guess you get a string, cause the CGI is just writing the response to the pipe and I suppose that is a well formed http response string. If this is the case proabably doesn't make sense to convert it to an HTTPResponse object to have to convert back to a string to send it through the socket. 

Anyway I can do this small modification also by myself it's not a big deal and then you can work on it when it's merged, but if you want you can already ... take it over?

**Comment by 552020** [comment]
> Ok I got it to run but couldn't connect, I didn't really looked at it though

This is what it does at the moments. It starts. If you mean to let the browser to get some web content served, this is at this stage an advanced feature @lmangall

**Comment by 552020** [comment]
> Yes the programs/scripts will return a well formatted string, if you need I can parse it to one a response object but yeah it might not be necessary

Ok. If the response is already formatted in a way that can be just sent back, than it makes no sense to parse it to an Http requeast object to parse it again to a string. It means that the function or method handling the request to the CGI will return a string and not an HTTPRequest object. No?

**Comment by lmangall** [comment]
Ok, I was expecting a connection message in the terminal and therefore thought something was wrong on my side

**Comment by 552020** [comment]
> Yeah what I want to do next is combine my branch (which awaits [your review](https://github.com/dantol29/webserver/pull/94)) and yours to a new one and have the code running, and doing it with a new handleCGIRequest (or a different approach) that is part of an object and set the meta-vars

What do you mean. My code was running! Not only compiling! Anyway I just submitted the review ... If you want you can also take over the whole routing/request handling part and design the way you want.

**Comment by lmangall** [comment]
> It means that the function or method handling the request to the CGI will return a string and not an HTTPRequest object. No?

Absolutely, actually it is the program or script being executed itself that will return a fully formatted string

**Comment by lmangall** [comment]
> What do you mean. My code was running! Not only compiling! Anyway I just submitted the review ... If you want you can also take over the whole routing/request handling part and design the way you want.

by running I just meant to integrate the CGI / different parts to the core, I am sure it is great the way you did it !

**Comment by lmangall** [comment]
I mad a temp branch from yours to check it out, here are a few things that prevented compilation:

```
src/HTTPResponse.cpp:48:35: error: no member named 'to_string' in namespace 'std'
        setHeader("Content-Length", std::to_string(body.size()));

```        
=> I used `template <typename T> std::string toString(const T &value)` from webserv,hpp
      
___________________________
       
```
src/Router.cpp:90:12: error: no member named 'back' in 'std::basic_string<char>
                if (path.back() != '/')

```                
=> this is c++11 on linux, I changed the line for ` if (!path.empty() && path[path.length() - 1] != '/')`

___________________________


```
src/server_utils.cpp:16:7: error: no member named 'transform' in namespace 'std'
        std::transform(headers.begin(), headers.end(), std::back_inserter(lowerHeaders), ::tolower);

```

This one was more tricky
`std::transform(headers.begin(), headers.end(), std::back_inserter(lowerHeaders), ::tolower);`
especially the std::back_inserter, my understanding is that it is used to append a result to the previous one

______________________________________

```
src/Server.cpp:356:27: error: no member named 'stoul' in namespace 'std'
                size_t chunkSize = std::stoul(chunkSizeLine, 0, 16);
```
refactored a bit readChunkedBody


_________________________________________

```
src/StaticContentHandler.cpp:52:16: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
        std::ifstream file(path);
                      ^    ~~~~
```
So apparently  std::ifstream in C++98 does not  accept a std::string object as an argument for its constructor; it requires a  (const char*).

changed `std::ifstream file(path);` to `std::ifstream file(path.c_str());`


_____________________________________________


=> you can cherrypick the following commit:

```
commit 0c115bcb17762331c787c93e7ca73bab9323e15d (HEAD -> lmangall-temp, origin/lmangall-temp)
Author: Leonard Mangallon <lmangall@c4c6c3.42berlin.de>
Date:   Wed Apr 10 23:57:54 2024 +0200

    solved cpp 98 linux vs mac compiling errors
```

**Comment by 552020** [comment]
Thanks for fixing all these thing! 🙏 I will just merge your branch into mine!

**Comment by lmangall** [comment]
No problem, these things were knew for me so I hope I didn't broke anything, also it seems like it was related to chunked request, so I remembered [your discussion](https://webservinc.slack.com/archives/C06R2QT1X4L/p1712603697721469) and while fixing it I thought that @dantol29 might already have a linux friendly version...

**Comment by 552020** [comment]
Till the 404 is working

image

I'm not sure anymore if it does what it promise, i.e. multiplexing. I could find a way to test it. Or better: I couldn't find a way to show that this version was more 'multiplexing' that the one we have in main. Also the first old version (the actual in main) seems to respond positively to ` url http://localhost:8080/ & curl http://localhost:8080/ & curl http://localhost:8080/`

Tomorrow I will do more tests

**Comment by 552020** [comment]
Take your time for test it, ask questions (if any) and improve it before let it looks good to you! ;-)

**Comment by dantol29** [comment]
### I still have errors that Leo fixed

### 1. 
```
no member named 'to_string' in namespace 'std'
        setHeader("Content-Length", std::to_string(body.size()));
```
We have `toString` in HTTPResponse class and `toString` template in the header. I renamed the one in the header to `toStringT`.

### 2. 
Why do we have `CGI_Handler.cpp` and `CGIHandler.cpp` it is so confusing.

### And all other errors that Leo solved...

_Maybe I cloned the wrong branch? Is it [slombard/web-36-implement-non-blocking-and-multiconnection-capabilities-with](https://github.com/dantol29/webserver/tree/slombard/web-36-implement-non-blocking-and-multiconnection-capabilities-with)_

**Comment by 552020** [comment]
> ### I still have errors that Leo fixed
> ### 1.
> ```
> no member named 'to_string' in namespace 'std'
>         setHeader("Content-Length", std::to_string(body.size()));
> ```
> 
> We have `toString` in HTTPResponse class and `toString` template in the header. I renamed the one in the header to `toStringT`.
> 

Did you `git pull` on that branch? Cause maybe you have an older version ... 

> ### 2.
> Why do we have `CGI_Handler.cpp` and `CGIHandler.cpp` it is so confusing.
> 
> ### And all other errors that Leo solved...
> _Maybe I cloned the wrong branch? Is it [slombard/web-36-implement-non-blocking-and-multiconnection-capabilities-with](https://github.com/dantol29/webserver/tree/slombard/web-36-implement-non-blocking-and-multiconnection-capabilities-with)_

Yes! CGI_Handler.cpp is Leo's code (and I didn't want to touch it), and CGIHandler an object, which is more a stub, I made. But it's a good point. I'll open an issue to combine the two files and then we can merge that branch in this one.

**Comment by dantol29** [comment]
You are right I had to pull changes.

@552020 I think my HTTPRequest returns 400, because you modify the request before calling the class. It is made to accept untouched request, otherwise it is not gonna work

**Comment by 552020** [comment]
> Some basic questions as I am exploring your code and trying to access pages:
> 
> 
> 
> - why `HTTPResponse StaticContentHandler::handleNotFound(void)` has the html hardcoded, instead of relying on a .html file, is it temporary, or a choice ?
> 

Temporary. This part is barely implemented.
> 
> 
> - in `void Server::handleConnection(int clientFD)` why is the following code legacy ?

Cause it's "hardcoded". GET and home. 
> 
> 
> 
> ```
> 
> StaticContentHandler staticContentHandler;
> 
> 			// This if condition only for legacy reasons! TODO: remove
> 
> 			if (request.getMethod() == "GET" &&
> 
> 				(request.getRequestTarget() == "/" || request.getRequestTarget() == "/home"))
> 
> 			{
> 
> 				response = staticContentHandler.handleHomePage();
> 
> 			}
> 
> 			else
> 
> 			{
> 
> 				response = staticContentHandler.handleRequest(request);
> 
> 			}
> 
> 			
> 
> 			
> 
> ```
> 
> 
> 
> 			
> 
> _______________________________
> 
> 			
> 
> 			
> 
> 
> 
> inside `void Server::handleConnection(int clientFD)`
> 
> you have :
> 
> ```
> 
> 		if (router.isDynamicRequest(request))
> 
> 		{
> 
> 			if (request.getMethod() == "GET" && request.getRequestTarget() == "/hello")
> 
> 			{
> 
> ```
> 
> and 
> 
> ```
> 
> bool Router::isDynamicRequest(const HTTPRequest &request)
> 
> {
> 
> 	if (request.getMethod() == "POST" || request.getMethod() == "DELETE")
> 
> 	{
> 
> ```
> 
> I think a request cannot have two methods, so why are you checking if a request is GET after router.isDynamicRequest returned true (meaning that it is POST or DELETE) ?

If is one OR (||) the other, if it's POST or DELETE then it will be dynamic. I don't know here if dynamic is the right term, an html file could have some JS going on and also be dynamic but not in the meaning of dynamic created content.
> 
>

**Comment by lmangall** [comment]
What I meant is that a request cannot have two methods, so there is no sense in checking if it is GET **after** you had a positive check (inside isDynamicRequest) on it being POST or DELETE...
or am I missing something ?

**Comment by 552020** [comment]
> What I meant is that a request cannot have two methods, so there is no sense in checking if it is GET **after** you had a positive check (inside isDynamicRequest) on it being POST or DELETE... or am I missing something ?

Ok. Now I understand what you mean

image

In this case the code would not work as expected cause we have an hello file, without extension but I left it there (as legacy code, in the sense that hello was a script I guess). The firt if condition in the 'isDynamicRequest' checks the method, if it is POST or DELETE it will dynamic. If it's a GET method could be dynamic or not. The second condition checks for the extension of the file of the target and if we have a match, then even if it's a GET request it will be considered a dynamic request and passed to the CGI. I guess 'hello' was in a `cgi-bin` folder, so we could also add a condition if the file is inside a `cgi-bin` folder, then it's dynamic. 


Answering more exactly to your question: passed the first if condition, we still don't know if the GET request will be dynamic (returning true, second if) or not, returning false (not entering the second if). 

Sorry, I didn't look at the code when I gave the first answer. Is it solved? :-)

**Comment by lmangall** [comment]
Just to make sure :
Do you still want to work on it before we review and pull or you would like us to review and pull ASAP ?
(if so there are conflicts with Environment.cpp and HTTPRequest.hpp)

**Review by dantol29 — APPROVED** [review]
That is the biggest PR I have ever seen!
Thank you for the documentation, really helps not to get lost in all that information.

If it is ready then LGMT!

**Comment by 552020** [comment]
> ## We MUST implement this
> ### 418 I'm a teapot
> This code was defined in 1998 as one of the traditional April Fools' jokes in RFC 2324, and is not expected to be implemented by actual HTTP servers. The RFC specifies this code should be returned by teapots requested to brew coffee. This HTTP status is used as an Easter egg in some websites, such as Google.com's "I'm a teapot" easter egg. Sometimes, this status code is also used as a response to a blocked request, instead of the more appropriate 403 Forbidden.

We already have it!

image

**Comment by 552020** [comment]
It is working again: @lmangall @dantol29 

image

**Comment by 552020** [comment]
image

**Comment by 552020** [comment]
I guess we can finally merge it, right? @lmangall @dantol29 

Not sure if it's doing multiplexing but at least it is doing what the previous version was doing with a lot more code!

**Review by lmangall — APPROVED** [review]
Great work, well done.
Nice to have the documentation, as instance about the history on multiplexing and meaning in a broader context.
Well done also for the last fixes to make it return the pages.

**Review by dantol29 — APPROVED** [review]
OK, LGMT! However, we have to find out why parser does not worn with the core

**Pull request merged**
