### PR TITLE
remove fd from vectors when socket are closed

### PR DESCRIPTION
**Pull request by 552020**
A first try. Can you check @dantol29 if the problem persist? And can you give me the request that trigger the bad file descriptor thing.

### CODE REVIEW

**Comment by dantol29** [comment]
```
./client $'POST / HTTP/1.1\r\nHost: www.example.com\r\nContent-type: multipart/form-data; boundary=stop_please\r\nContent-length: 42\r\n\r\nblablabla\r\n\r\n'
```
@552020 This is the test request. 

./client is located at docs/daniil_socket

**Comment by 552020** [comment]
Did you check if the problem persist (on this branch)? @dantol29 

Cause I tested it now with the request you posted above but I didn't get the bad file descriptor error

image

**Comment by dantol29** [comment]
OK, I will test ASAP.
Would be nice to put all those comments in a operator<< overload of it is possible in this case.

**Comment by 552020** [comment]
> Would be nice to put all those comments in a operator<< overload of it is possible in this case.

Sure, but what do you mean? Ok. I guess I understand what you mean. Yes we can do this but it will work only for objects, like when we print an object.

**Comment by dantol29** [comment]
@552020 Why when I run that test request I do not see `std::cout << "Received HTTP request: " << std::endl << httpRequestString << std::endl;` this part in the terminal printed out?

**Comment by 552020** [comment]
> @552020 Why when I run that test request I do not see `std::cout << "Received HTTP request: " << std::endl << httpRequestString << std::endl;` this part in the terminal printed out?

I'll investigate.

**Comment by 552020** [comment]
Can you check again if it is working (check also if your request is well formed, i.e. if the declared body size in the header corresopnd to the size of the body)? And could you help me to solve this issue: https://linear.app/web-serv/issue/WEB-122/help-stefano-to-fix-content-length-retrieval-feature-in-daniils-client!

**Comment by dantol29** [comment]
image
It still does not work

```
./client $'POST / HTTP/1.1\r\nHost: www.example.com\r\nContent-type: multipart/form-data; boundary=stop_please\r\nContent-length: 3\r\n\r\nbla\r\n\r\n' 
```

**Comment by 552020** [comment]
Did you pull the branch? Cause it shoud print more information ...

I also open a PR regarding the parsing discussion in the core: https://linear.app/web-serv/issue/WEB-123/decide-if-the-core-has-to-do-any-parsing-at-all-or-not

**Comment by dantol29** [comment]
_Of course I did not pull!_

## NOW IT WORKS! thanks!

lets merge ASAP!

**Review by dantol29 — APPROVED** [review]
WORKS!

**Review by lmangall — APPROVED** [review]
Well done, I know you guys checked this enough so I just reviewed the files and don't make you wait for my review.

**Pull request merged**
