### PR TITLE
Slombard/web 130 implement most logical option

### PR DESCRIPTION
**Pull request by lmangall**
Stefano's code that we just made work with the last version of the main.

The HTTPRequest object has been split into a parser object and an HTTP Request object. Overall minimal changes, rather moving things around, as instance:
- The request has no status code, the status code now belong to the response (initialized to 0), if the parser finds an error it sets the status on the response. 
- The parsing that you previously started in the constructor  is now at the beginning of parseRequestLine   

This is the first step towards the core not parsing

### CODE REVIEW

**Review by dantol29 — COMMENTED** [review]
1.ParseRequestLine should be named differently because request line is "GET / HTTP/1.1", but it parses the whole request.

2. I can't find Parse.cpp.

**Comment by dantol29** [comment]
Okay, I found Parse.cpp and look like in the implementation we call parseRequestLine, parseHeaders and parseBody separately?

**Comment by 552020** [comment]
> 1.ParseRequestLine should be named differently because request line is "GET / HTTP/1.1", but it parses the whole request.
> 
> 2. I can't find Parse.cpp.

1. That's true. We could call it call it just parseRequest, and we could move the code parsing the request line into a 'new' parseRequest Line. 

> Okay, I found Parse.cpp and look like in the new implementation we call parseRequestLine, parseHeaders and parseBody separately?

The code from the constructor has been moved into parseRequestLine but now, parseHeader and parseBody are called at the end of parseRequestLine. But I see now that it's dumb, I was thinking of parseRequestLine, like parseRequestString. I'll change the names and restore the 'old' scheme of the constructor in the parseRequest method.

**Comment by 552020** [comment]
Changed @dantol29

**Comment by lmangall** [comment]
@552020 you have to approve your own PR

I opened the PR because we pushed the last commit from my computer, but I would approve it now:
_LGTM, looking forward to the step 2_

**Comment by 552020** [comment]
> @552020 you have to approve your own PR
> 
> I opened the PR because we pushed the last commit from my computer, but I would approve it now:
> LGTM, looking forward to the step 2

@lmangall I wait first for Daniil @dantol29 to ask for more changes (or explanation) and to approve it, before I'll approve it.

**Review by dantol29 — APPROVED** [review]
Now, with the parseRequest, it makes much more sense!

LGTM!

**Review by 552020 — APPROVED** [review]
Best PR I've ever seen. Great job @lmangall!

**Pull request merged**
