### PR TITLE
Slombard/web 199 add ngnix in a docker

### PR DESCRIPTION
**Pull request by 552020**
Adding NGNIX source code and a Dockerfile to run it. 
- So we can check how NGNIX is doing things
- Eventually run the tests also against NGNIX and check if we get the same results.

### CODE REVIEW

**Review by lmangall — DISMISSED** [review]
Great idea, for the tests we also have to go back to Siege

**Comment by lmangall** [comment]
@552020 I don't know if you have seen it but here as well you have "The merge-base changed after approval" message. Daniil told me that you found the source of this problem (merging an open PR into another open PR) yesterday

**Comment by 552020** [comment]
It could be about merging a branch into another branch. This branch actually has only 1 relevant commit, the last one. The precedent ones are from other branches I built on. Like I wrote branch A, the from branch A I opened B, the from branch B I opened C and so on. This branch has code from all these 'old' branches. And only the last commit is relevant to it. I'll try maybe to rebase it and hold all the last commit. If I understand what rebase it.

**Comment by 552020** [comment]
I'm going the rebase way. There is a practical command you can use `git rebase -i main`. Git will find all the commits from which the branch is diverging from main by itself ...

**Comment by 552020** [comment]
Before rebase

image

After rebase

image

**Review by lmangall — DISMISSED** [review]
LGTM!

**Comment by 552020** [comment]
@dantol29

**Comment by dantol29** [comment]
@552020 I think Leo meant Dockerfile is missing

**Comment by 552020** [comment]
> @552020 I think Leo meant Dockerfile is missing

Added!

**Comment by dantol29** [comment]
@552020 I get an error:
image

**Comment by 552020** [comment]
> @552020 I get an error: image

This should be fixed now. .gitignore was presenting the commit of the configure file

**Review by lmangall — DISMISSED** [review]
Nice, thank you !

**Comment by 552020** [comment]
@dantol29 should be fixed now. Sorry it tool so long!

**Comment by lmangall** [comment]
@552020 you got conflicts

**Comment by dantol29** [comment]
I started container, attached shell to it, but could not start NGINX
image

**Comment by 552020** [comment]
image

Did you read the README.md?

**Comment by lmangall** [comment]
@552020 you got conflicts

**Comment by 552020** [comment]
@dantol29 @lmangall conflicts solved.

**Review by lmangall — APPROVED** [review]
LGTM!

**Comment by 552020** [comment]
@dantol29

**Review by dantol29 — APPROVED** [review]
After 11 days of debugging I can finally approve this PR!

**Comment by 552020** [comment]
It was working form the (almost) beginning! :-)

**Pull request merged**
