### PR TITLE
readme updated

### PR DESCRIPTION
**Pull request by lmangall**
from https://linear.app/web-serv/issue/WEB-16/test-issue-for-leo

### CODE REVIEW

**Review by dantol29 — APPROVED** [review]
That is a real README!🚀

**Comment by 552020** [comment]
Pity I've not been selected as a reviewer!  🙁

**Comment by lmangall** [comment]
@552020  As far as I know you are. 2 review are required and only yours now is missing. 
Or is there a way to explicitly write somebody as a reviewer ?

**Comment by lmangall** [comment]
Alright, saw your message in #12 and added you as a reviewer

**Review by 552020 — CHANGES_REQUESTED** [review]
How strict should I be with my review? Or being this a test issue, should I pass everything?

My critic would be that this being the README of the project should give first the basic information about the project itself, style should be impersonal and brief (Resources instead of "Last resourced I have been checking out (Leo's selection)' and not out of context "Allowed functions". 

But if you mean it's just about completing the linear workflow and we don't care about having a well curated README I can pass approve the MR without further modifications. ;-)

**Comment by lmangall** [comment]
The Linear was "Add something into the README" si I did just that. 
This document is the very first thing we see when we open the page ("we" because nobody else is going to open it, especially before it's done). So while in development I personnaly treat the Readme as notes on the repo and as an help for myself rather than for people visiting the page. Which is indeed a point I didn't made clear.
I think it is useful to collect links or important information we might want to check or verify while we develop this application. That is why I had "Last resourced I have been checking out (Leo's selection)'" : you both can add your own list so if the others want to check it they can, or you can add the crucial information you think should be present in the first page of the repo when we open it. And perhaps when the project is done we can turn this Readme into a form that fulfils its conventional purpose.
I even think the Readme should be the exception to the "no push to main" rule. When you open the repo you have the Readme and on its right a pencil icon so you can edit it right on, really easily...

**Review by 552020 — APPROVED** [review]
LGTM

**Pull request merged**
