### PR TITLE
add Debugging class with log function and a test function

### PR DESCRIPTION
**Pull request by 552020**
You can read in the related linear issue what this is about: https://linear.app/web-serv/issue/WEB-194/add-printing-debug-class

### CODE REVIEW

**Review by dantol29 — DISMISSED** [review]
I like it! Such a great way to get rid of unnecessary information if you want to!

LGTM!

**Comment by 552020** [comment]
Solved new conflicts here: this needs to be reapproved again.

**Review by dantol29 — DISMISSED** [review]
OK!

**Comment by 552020** [comment]
@dantol29: you need to re-accept this cause I had to solve conflicts with main. 
@lmangall: ready to be merged: you can check and eventually approve.

**Comment by 552020** [comment]
@dantol29 @lmangall conflicts are solved now

**Review by dantol29 — APPROVED** [review]
LGTM! Will definitely used it

**Review by lmangall — APPROVED** [review]
LGTM!

**Pull request merged**
