### PR TITLE
Parse body and more tests

### PR DESCRIPTION
**Pull request by dantol29**
I added parseBody member function that stores each line of a body in the `std::vector<std::string> _body`.

Also I made more tests for headers and body in the `tests.cpp` file

### CODE REVIEW

**Review by 552020 — APPROVED** [review]
LGTM: nice!

I didn't understand how the test work. compiled the test.cpp file and I run it like ./test "simple" is this correct. But then nothing happen. 

After I'm done (hopefully soon) with my branch we should compare our work on the chunked bodies cause I also wrote some logic for that. 

I have also a class HTTPResponse with a method setStatusCode, to set the statusCode on the response object ...

**Comment by dantol29** [comment]
Hmm, it should work.
@552020 
Did you launch webrowser before launching the tests?

**Comment by 552020** [comment]
> Hmm, it should work. @552020 Did you launch webrowser before launching the tests?

🙈 It works sorry! I didn't launch the server before I was kind of expecting something coming out from the terminal where I run test ...

**Review by lmangall — APPROVED** [review]
I did some tests and it all seems to working fine

**Pull request merged**
