### PR TITLE
Create three directories representing hosted websites

### PR DESCRIPTION
**Pull request by 552020**
I implemented three directories with three websites, 1 in Perl, 1 in PHP, 1 in Python. 

The websites are in the folder /var/www/. This is the directory where normally web content in a Linux system would be placed. This directory would not be 'inside' the server, but the server would have in its configuration the possibility to specify the folder where it should look for web content. 

For let them work, proper routing needs to be written. 

This is the linear issue: https://linear.app/web-serv/issue/WEB-71/create-three-directories-representing-hosted-websites

### CODE REVIEW

**Comment by lmangall** [comment]
It doesnt compile, you have to remove the ft_memeset in main (it is in utlis) and modify the Makefile:
`# Compiler and Flags
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98 -I. -Iinclude
DEPFLAGS = -MMD -MP

# Source and Object Files
SRCS = main.cpp \
	Server.cpp \
	RequestHandler.cpp \
	CGIHandler.cpp \
	Environment.cpp \
	Utils.cpp
OBJDIR = obj
OBJS = $(addprefix $(OBJDIR)/, $(SRCS:.cpp=.o))

# Main Target
TARGET = webserv

# Build Rules
all: $(OBJDIR)  $(TARGET)

# Ensure the OBJDIR exists before compiling anything
$(OBJDIR):
	mkdir -p $(OBJDIR)

# Rule for compiling source files into object files
$(OBJDIR)/%.o: %.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -c $< -o $@

# Linking the main target
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Cleaning up the build
clean:
	rm -rf $(OBJDIR)
	rm -f $(TARGET)

fclean: clean
	rm -f $(TARGET)

re: fclean all

.PHONY: all clean fclean re`

I believe this is a problem from my code which got accepted and pushed to main

**Comment by lmangall** [comment]
Otherwise really fast and really good job, too bad we can't see it yet, but I understand that you let the routing for another issue

**Review by lmangall — CHANGES_REQUESTED** [review]
As per my previous comment changes to main.cpp and Makefile are needed

**Comment by 552020** [comment]
I merged now main into the branch. It should work, since I didn't change anything from main.

**Review by dantol29 — APPROVED** [review]
Hah, the story about Moskovitz is really funny)

Overall, looks great. Hard to test it though, because it is not connected to the code.

**Comment by dantol29** [comment]
It is crazy that only 20 people showed up to his lecture. Looks like people did not understand the potential of Facebook at that time

**Review by lmangall — APPROVED** [review]
Allgood now

**Pull request merged**
