### PR TITLE
First CGI

### PR DESCRIPTION
**Pull request by lmangall**
A CGI script is essentially an executable program that can be written in any programming language capable of being executed by the operating system.

I will next explore either more compley script (something in relation with the Methods) or the CGI part of the core...

Making a PR to conform to our "push and PR often policy"

### CODE REVIEW

**Comment by 552020** [comment]
Great! (Assign the reviewers is important, otherwise we don't get notified! :-)

**Comment by 552020** [comment]
I commented in linear about this. I'm not sure what I'm supposed to review here.

**Review by dantol29 — APPROVED** [review]
Looks good and readable!

**Comment by 552020** [comment]
I close this one superseded by #25

**Pull request closed without merging**
