### PR TITLE
Lmangall/web 219 use a config object in the core and router

### PR DESCRIPTION
**Pull request by lmangall**
@lmangall and @dantol29 changed almost everything from this issue: 

`https://linear.app/web-serv/issue/WEB-244/discuss-config-and-serverblock-objects`
 
 Now ServerBlock and Config classes are more clear and readable!
 
 (Daniil) I have some questions that I wrote under unsolved checks

### CODE REVIEW

**Review by dantol29 — APPROVED** [review]
LGTM!

**Comment by 552020** [comment]
> @lmangall and @dantol29 changed almost everything from this issue:
> 
> `https://linear.app/web-serv/issue/WEB-244/discuss-config-and-serverblock-objects`
> 
> Now ServerBlock and Config classes are more clear and readable!
> 
> (Daniil) I have some questions that I wrote under unsolved checks

Where are the questions under the unsolved checks? @dantol29

**Comment by 552020** [comment]
The name of the commits are a little bit messy a rebase of the branch is absolutely necessary! @lmangall I would just squash the ones that are not meaningful anymore for the history of the repo. @lmangall :-)

**Review by 552020 — CHANGES_REQUESTED** [review]
Good improvements! 

The are still things named variable or var going on. I did also some comments in the linear issue.

**Comment by dantol29** [comment]
## @552020 Now it is improved even more

1. Config config(argv[1]); config object is created with constructor
2. all the checks are removed from the main. Now it is clean.
3. repetiotion avoided in the constructor

**Review by 552020 — APPROVED** [review]
LGTM!

**Review by dantol29 — APPROVED** [review]
Last commit is on fire!!

**Pull request merged**
