### PR TITLE
Dtolmaco/web 206 add real tests to the GitHub actions

### PR DESCRIPTION
**Pull request by dantol29**
Github Actions are setup!

## 4. Possibly Leo's tester, but I think it is not ready yet

### CODE REVIEW

**Comment by 552020** [comment]
Why is this still open? Don't we have the tests already integrated? @dantol29

**Comment by dantol29** [comment]
@552020 No, they are integrated only in this branch. In order for them to work, we have accept this PR

**Review by lmangall — APPROVED** [review]
Great work!

**Review by 552020 — APPROVED** [review]
LGTM

**Pull request merged**
