### PR TITLE
Basic server and client communication (works like minitalk)

### PR DESCRIPTION
**Pull request by dantol29**
tutorial: https://www.geeksforgeeks.org/socket-programming-in-cpp/

TO TEST:
1. c++ server.cpp -o server
2. ./server  - now server is listening
3. c++ client.cpp -o client
4. ./client "HELLO SERVER!"

Feel free too request changes!

### CODE REVIEW

**Comment by 552020** [comment]
After the creation of the PR you should also specify the reviewers, even if it's clear who they will be (just so that we get the notification) or alternatively announce the MR in Slack like posting the link to this page. Now I did it by myself so Leo will know. 

In general every branch should be tied to an issue in linear.

**Review by lmangall — APPROVED** [review]
Thank you. Interesting that "this" is also an API, and probably the same kind of API as we know, only with a slighthly different use.

Don't forget to pull main into the branch before merging it to solve conflicts beforehand

**Comment by 552020** [comment]
@lmangall approved this PR so I ask myself how did he manage to let it work. How did you manage Leo?

I try now to compile both programs, they compile. I started the server, then  I started the client, but the client gives a seg fault. 

image

**Review by 552020 — CHANGES_REQUESTED** [review]
The client is segfaulting.

**Comment by lmangall** [comment]
I had no segfault (running on Mac), I followed Daniil instructions and didn't do anything extra

**Comment by lmangall** [comment]
I just git pulled, tested again and it works fine @552020 
The server doesn't have any exit so you have to ctrl+c it but that's all

Screenshot 2024-03-28 at 16 23 11

**Comment by dantol29** [comment]
I fixed the segfault. It segfaulted when no arguments were passed.

**Review by 552020 — APPROVED** [review]
LGTM

**Comment by 552020** [comment]
@lmangall need to approve again!

**Review by lmangall — APPROVED** [review]
Great!

**Pull request merged**
