### PR TITLE
Dtolmaco/web 297 implement clean log output

### PR DESCRIPTION
**Pull request by dantol29**
For now it looks like this

image

### CODE REVIEW

**Comment by dantol29** [comment]
[UPDATE]
image

**Comment by 552020** [comment]
Is this still actual? There are conflicts anyway! @dantol29

**Comment by dantol29** [comment]
@552020 It has to be done anyway

**Comment by 552020** [comment]
@dantol29 This is still a draft, and it has still conflicts.

**Comment by dantol29** [comment]
@552020 I gonna merge at the very end

**Comment by dantol29** [comment]
Too many conficts....

**Pull request closed without merging**
