### PR TITLE
1 Added the list of links to the helpful resources

### PR DESCRIPTION
**Pull request by dantol29**

### CODE REVIEW

**Review by lmangall — APPROVED** [review]
Cool, the issue @552020 assigned me is also on the Readme so I will make a branch from yours, or similar approach, to avoid conflicts. Still this branched should be merged before mine.
It's good lil practice.

**Comment by lmangall** [comment]
Any idea why when I check the branch on github : https://github.com/dantol29/webserver/tree/create-a-readme-file-with-links-to-helpful-resources

or on git :
`➜  webserv_dantol git:(main) git branch -a       
➜  webserv_dantol git:(main) git checkout -b remotes/origin/create-a-readme-file-with-links-to-helpful-resources
Switched to a new branch 'remotes/origin/create-a-readme-file-with-links-to-helpful-resources'
➜  webserv_dantol git:(heads/remotes/origin/create-a-readme-file-with-links-to-helpful-resources) 
➜  webserv_dantol git:(heads/remotes/origin/create-a-readme-file-with-links-to-helpful-resources) ls README.md 
README.md
➜  webserv_dantol git:(heads/remotes/origin/create-a-readme-file-with-links-to-helpful-resources) cat README.md 
# webserver

Our own HTTP server!`

I cannot see @dantol29 last version of the README ?

**Comment by dantol29** [comment]
> Any idea why I cannot see @dantol29 last version of the README ? When I check the branch on github : https://github.com/dantol29/webserver/tree/create-a-readme-file-with-links-to-helpful-resources
> 
> or on git :
> 
> ```shell
> ➜  webserv_dantol git:(main) git branch -a       
> ➜  webserv_dantol git:(main) git checkout -b remotes/origin/create-a-readme-file-with-links-to-helpful-resources
> Switched to a new branch 'remotes/origin/create-a-readme-file-with-links-to-helpful-resources'
> ➜  webserv_dantol git:(heads/remotes/origin/create-a-readme-file-with-links-to-helpful-resources) 
> ➜  webserv_dantol git:(heads/remotes/origin/create-a-readme-file-with-links-to-helpful-resources) ls README.md 
> README.md
> ➜  webserv_dantol git:(heads/remotes/origin/create-a-readme-file-with-links-to-helpful-resources) cat README.md 
> # webserver
> 
> Our own HTTP server!
> `
> ```

Because it is not readme.md, it is resources.md

**Comment by lmangall** [comment]
Thanks, I still can't see it on my local git but that's probably something off on my side, like the local not tracking an upstream branch

**Comment by 552020** [comment]
image

But the issue seems to have been opened with Linear. So I don't get it...

**Comment by 552020** [comment]
Ok. Now I found it. 

image

On the top right cornert you will find the icon to the automatic created issue. It should be something like: dtolmaco/web-12-create-a-readme-file-with-links-to-helpful-resources.

To change the name of a branch just do: `git branch -m old-name new-name`

**Comment by lmangall** [comment]
Thanks, really useful info

**Pull request closed without merging**
